my_app/main/forms.py
from flask import current_app
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, HiddenField
from wtforms.validators import Length, DataRequired, NumberRange

from unidecode import unidecode
from my_app.models import Riddle


# Vérifie la liste des mots autorisés pour l'énigme.
def validate_riddle(form,field):
    not_accepted_words = ['enigme','reponse'] #liste non exhaustive...
    strField = (unidecode(field.data)).lower()  #retire les accents et met en minuscules
    for word in not_accepted_words:
        if word in strField:
            form.riddle.errors.append("Le mot \'{}\' n'est pas autorisé !".format(field.data))

# Vérifie si la valeur du champ n'est pas déjà présente en DB
#def isUnique_riddle(form, field):
#    if Riddle.query.filter_by(riddle=field.data).first():
#        form.riddle.errors.append("L'énigme existe déjà en DB !")

class RiddleForm( FlaskForm ):
    id = HiddenField("riddle_id")
    riddle = StringField("Enigme : ",
                           validators=[DataRequired(message="Le champ ne peut être vide !"),
                                       Length(min=10,max=250, message="L\'énigme doit comporter entre %(min)d et %(max)d caractères !"),
                                       validate_riddle])
    answer = StringField("Réponse : ",
                           validators=[DataRequired(message="Le champ ne peut être vide !"),
                                       Length(max=100, message="La réponse ne peut comporter plus de %(max)d caractères !"),
                                       validate_riddle])
    clue = StringField("Indice : ",
                       validators=[Length(max=100, message="L'indice ne peut comporter plus de %(max)d caractères !")])
    level = IntegerField("Niveau : ",
                         validators=[DataRequired(message="Veuillez entrer une valeur !"),
                                     NumberRange(min=0, max=10, message="Le niveau de difficulté doit être compris entre %(min)d et %(max)d !")
                                                        ])
    submit = SubmitField("Ajouter")

class ClueForm( FlaskForm ):
    id = HiddenField("clue_id")
    clue = StringField("Clue : ",
                       validators=[Length(max=100, message="L\'indice ne peut comporter plus de %(max)d caractères !")])
    riddle = StringField("Enigme :", render_kw={'readonly': True})
    riddle_id = HiddenField("riddle_id")
    submit = SubmitField("Ajouter")

my_app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from my_app.main import views

my_app/main/views.py
from flask import render_template, redirect, url_for, request, flash, abort, jsonify,json
from flask import current_app
from flask_login import login_required, current_user, logout_user

from my_app.main import main
from my_app.main.forms import RiddleForm, ClueForm
from my_app import db
from my_app.models import Riddle, Clue, User

@main.route('/')
@login_required
def index():
    return list_riddle()
@main.route('/infos')
def infos():
    return render_template('main/infos.html')

@main.route('/liste', methods=['GET','POST'])
@login_required
def liste():
    return list_riddle()

""" *******************
    Controller : Riddle
    *******************
"""
@main.route('/list_riddle', methods=['GET'])
@login_required
def list_riddle():
    validate_user()
    page = request.args.get('page', 1, type=int)
    per_page = 5
    tot_page = 2

    if current_user.admin:
        pagination = Riddle.query.paginate(page=page, per_page=5)
    else:
        pagination = Riddle.query.filter(Riddle.user_id == current_user.id).paginate(page=page, per_page=5)

    riddles = pagination.items
    return render_template('main/list_riddle.html', riddles=riddles, current_user=current_user, pagination=pagination, tot_page = tot_page, per_page = per_page)

@main.route('/list_riddle_ajax',methods=['GET','POST'])
@login_required
def list_riddle_ajax():
    page = request.args.get('page', 1, type=int)
    validate_user()
    per_page = 5
    tot_page = 20

    if current_user.admin:
        pagination = Riddle.query.paginate(page=page, per_page=5)
    else:
        pagination = Riddle.query.filter(Riddle.user_id == current_user.id).paginate(page=page, per_page=5)

    riddles = pagination.items
    dict = {
        "riddles":riddles,
        "per_page":per_page,
        "tot_page":tot_page,
    }
    return jsonify(dict)

@main.route('/create_riddle', methods=['GET','POST'])
@login_required
def create_riddle():
    validate_user();
    form = RiddleForm()
    form.id.data = 0
    return render_template("main/create_riddle.html",form=form, current_user=current_user, action="Create")

@main.route('/update_riddle', methods=['GET'])
@login_required
def update_riddle():
    validate_user();

    id = request.args.get('riddle_id')
    riddle = Riddle.query.filter_by(id=id).first()

    if not (current_user.admin) and not (riddle.user_id == current_user.id):
        abort(403)

    form = RiddleForm()

    if riddle:
        form.id.data = riddle.id
        form.riddle.data = riddle.riddle
        form.answer.data = riddle.answer
        form.level.data = riddle.level
    else:
        flash("Cette énigme n\'existe pas !", 'Danger')
        return redirect(url_for('main.list_riddle'))

    return render_template("main/create_riddle.html", form=form, current_user=current_user, action="Update")

@main.route('/save_riddle',methods=['POST'])
@login_required
def save_riddle():
    validate_user();

    form = RiddleForm()
    action = "Create"

    if form.validate_on_submit():

        id = int(form.id.data)
        riddle = form.riddle.data
        answer = form.answer.data
        clue = form.clue.data
        level = int(form.level.data)

        # Créer ou mettre à jour l'énigme
        if id != 0:
            riddle_record = Riddle.query.filter_by(id=id).first()
            riddle_record.riddle = riddle
            riddle_record.answer = answer
            riddle_record.level = level
            action = "Update"
            message = "L'énigme a été modifiée !"
        else:
            riddles = Riddle.query.filter_by(riddle=riddle).first()
            action = "Create"
            # On supposera que l'énigme doit être unique pour tous les utilisateurs; sinon modifier le modèle pour la rendre unique par utilisateur.
            if riddles:
                flash("L\'énigme existe déjà en DB !", "Danger")
                return render_template("main/create_riddle.html", form=form, current_user=current_user, action=action)
            else:
                riddle_record = Riddle(riddle=riddle, answer=answer, level=level, user_id=current_user.id)
                action = "Create"
                message = "L'énigme a été créée !"

        db.session.add(riddle_record)

        #Créer ou mettre à jour l'indice
        if clue != '':
            clue_record = Clue(clue=clue, riddle=riddle_record)
            db.session.add(clue_record)

        db.session.commit()
        flash(message, 'Success')
        return redirect(url_for('main.create_riddle')) #To avoid re-submitting a post request on 'Refresh page'.
    else:
        return render_template("main/create_riddle.html",form=form, current_user=current_user, action=action)


@main.route('/delete_riddle', methods=['GET'])
@login_required
def delete_riddle():
    validate_user();

    id = request.args.get('riddle_id')
    riddle = Riddle.query.filter_by(id=id).first()

    if not (current_user.admin) and not (riddle.user_id == current_user.id):
        abort(403)

    try:
        db.session.delete(riddle)
        db.session.commit()
    except BaseException as e:
        flash("L'énigme n'a pas été supprimée : "+ str(e),"Warning")

    #return list_riddle()
    return list_riddle_ajax()

@main.route('/level', methods=['GET'])
@login_required
def level():
    validate_user()

    riddle_id = request.args.get("riddle_id")
    direction = request.args.get("direction")
    level_min = current_app.config['LEVEL_MIN']
    level_max = current_app.config['LEVEL_MAX']


    logged_user = User.query.filter_by(id=current_user.id).first()
    riddle = Riddle.query.filter_by(id=riddle_id).first()

    if not(logged_user.admin or riddle.user_id == current_user.id):
        flash("Vous n'êtes pas autorisé à modifier cette énigme !", "Danger")
        #abort(403)
        return redirect("/liste")

    if (direction == 'up'):
        if (riddle.level< level_max):
            riddle.set_level(riddle.level + 1)
    else:
        if (riddle.level > level_min):
            riddle.set_level(riddle.level - 1)

    db.session.commit()

    return str(riddle.level)



""" ********************
    Controller : Clue
    ********************
"""
@main.route('/list_clues',methods=['GET'])
@login_required
def list_clues():
    validate_user();


@main.route('/clue', methods=['GET'])
@login_required
def clue():
    validate_user();

    riddle_id = request.args.get('riddle_id')
    clue_id= request.args.get('clue_id')
    clue = Clue.query.filter_by(id=clue_id).first()
    riddle = Riddle.query.filter_by(id=riddle_id).first()
    form = ClueForm()

    if not (current_user.admin) and not (riddle.user_id == current_user.id):
        abort(403)

    if clue:
        template = "main/update_clue.html"
        form.id.data = clue.id
        form.clue.data = clue.clue
        form.riddle.data = clue.riddle.riddle
        form.riddle_id.data = riddle_id
    else:
        template = "main/create_clue.html"
        form.id.data = 0
        form.clue.data= ""
        form.riddle.data = riddle.riddle
        form.riddle_id.data = riddle_id

    return render_template(template, form=form)

@main.route('/save_clue',methods=['POST'])
@login_required
def save_clue():
    validate_user();

    form = ClueForm()

    id = int(form.id.data)
    riddle_id=int(form.riddle_id.data)
    clue = form.clue.data

    if id != 0:
        clue_record = Clue.query.filter_by(id=id).first()
        message = "L'indice a été modifié !"
    else:
        clue_record = Clue(clue=clue,riddle_id=riddle_id)
        message = "L'indice a été créé !"

    if form.validate_on_submit():
        clue_record.clue = clue
        clue_record.riddle_id = riddle_id
        db.session.add(clue_record)
        db.session.commit()
        flash(message, 'Success')
        return redirect(url_for('main.list_riddle')) #To avoid re-submitting a post request on 'Refresh page'.
    else:
        return render_template("main/create_clue.html",form=form)

@main.route('/delete_clue', methods=['GET'])
@login_required
def delete_clue():
    validate_user();

    riddle_id=request.args.get('riddle_id')
    clue_id=request.args.get('clue_id')
    clue = Clue.query.filter_by(id=clue_id).first()
    riddle = Riddle.query.filter_by(id=riddle_id).first()

    if not (current_user.admin) and not (riddle.user_id == current_user.id):
        abort(403)

    if clue:
        try:
            db.session.delete(clue)
            db.session.commit()
            #flash("L'indice a été supprimé !", "Success")
        except BaseException as e:
            flash("L'indice n'a pas été supprimé : "+ str(e),"Warning")
    else:
        flash("Il n'y pas d'indice pour cette énigme ! ", "Warning")

    return json.dumps({'success':True}), 200, {'ContentType':'application/json'}

""" ********************
    Helper functions :
    ********************
"""
def validate_user():
    if current_user.blocked:
        flash('Your account has been blocked by an administrator.', 'Danger')
        logout_user()
        return redirect(url_for('auth.login'))
    else:
        return

""" ********************
    Controller : Error Pages
    ********************
"""
@main.app_errorhandler(404)
def page_not_found(e):
     return render_template("errors/404.html"), 404

@main.app_errorhandler(500)
def internal_server_error(e):
    return render_template("errors/500.html"), 500

my_app/templates/main/create_clue.html
{% extends "main.html" %}
{% block body %}
<h1>Create clue :</h1>
<form method="POST" action="{{ url_for('main.save_clue') }}">
    {% include 'main/main_clue.html' %}
    {{ form.submit(class="btn btn-primary", value="Create") }}
</form>
{% endblock %}

my_app/templates/main/create_riddle.html
{% extends "main.html" %}
{% block body %}
<h1>Créer vos énigmes :</h1>
<form method="POST" action="{{ url_for('main.save_riddle') }}">
    {{ form.csrf_token }}
    {{ form.id() }}
    <div class="form-group row" style="margin-bottom:10px">
        {{ form.riddle.label(class="col-sm-1 col-form-label") }}
        <div class="col-sm-8">
            {{ form.riddle(type="text",class="form-control",placeholder="Encodez votre énigme ici...") }}
            {% if form.errors %} {% for message in form.riddle.errors %} {{ message }} {% endfor %} {% endif %} <br/>
        </div>
    </div>
    <div class="form-group row" style="margin-bottom:10px">
        {{ form.answer.label(class="col-sm-1 col-form-label") }}
        <div class="col-sm-8">
            {{ form.answer(type="text",class="form-control",placeholder="Encodez sa réponse ici...") }}
            {% if form.errors %} {% for message in form.answer.errors %} {{ message }} {% endfor %} {% endif %} <br/>
        </div>
    </div>
    <div class="form-group row" style="margin-bottom:10px">
        {{ form.level.label(class="col-sm-1 col-form-label") }}
        <div class="col-sm-2">
            {{ form.level(class="form-control") }}
            {% if form.errors %} {% for message in form.level.errors %} {{ message }} {% endfor %} {% endif %} <br/>
        </div>
    </div>
    {{ form.submit(class="btn btn-primary", value=action) }}
</form>
{% endblock %}

my_app/templates/main/infos.html
{% extends "main.html" %}
{% block body %}
<h1 class="vicious">Vicious clues</h1>
<h2>Login : </h2>
Pour les besoins de l'exercice, les identifiants sont :<br/>
Login : <b>olivier.biard@student.unamur.be</b><br/>
Mot de passe : <b>ihdcb336</b></br>
Cet utilisateur est 'administrateur'.
<h2>Présentation :</h2>
Vicious clues vous introduit au monde des 'Escape Games'.<br/>
Vous serez amenés à répondre à des énigmes; et ainsi progresser de niveau en niveau.
<h2>Fonctionnalités :</h2>
Les fonctionnalités sont actuellement limitées; mais celles-ci sont appelées à évoluer.<br/>
Pour pouvoir y accéder, vous devez d'abord vous authentifier !<br/>
Parmi celles déjà présentes, l'on trouvera :<br/>
<h3>Créer ses énigmes :</h3>
Enigme : introduisez ici la question qui fera figure d'énigme.<br/>
Réponse : introduisez ici la réponse à cette énigme.<br/>
Niveau : niveau de difficulté auquel vous voulez associer l'énigme.<br/>
<h3>Afficher ses énigmes :</h3>
En cliquant sur le menu 'Liste des énigmes', ou en utilisant le suffixe /liste dans l'url, vous pouvez afficher la liste des énigmes.<br/>
Pour chaque éngime, vous pouvez afficher / cacher sa réponse en cliquant sur le bouton 'show/hide'.<br/>
Vous pouvez également ajuster son niveau avec les flèches.  Attention : le niveau ne peut être inférieur à 0 !<br/>
{% endblock %}

my_app/templates/main/list_riddle.html
{% extends "main.html" %}
{% block body %}
<h1>Liste des énigmes</h1>
{% set count = namespace(value=0) %}
{% for riddle in riddles %}

    <div class="riddlediv" id="riddlediv_{{count.value}}" style="border:1px solid;margin-bottom:10px;padding:5px 5px 5px 5px">
    {% set count.value = count.value +1 %}
        <!-- Partie concernant l'énigme elle-même -->
            <div class="riddleid" style="display:none">{{ riddle.id }}</div>
            <div class="riddle" style="margin-bottom:5px"><b>Enigme : </b>{{ riddle.riddle }}</div>
            <div class="answer" style="display:none;margin-bottom:5px"><b><i>Réponse : </b></i>{{ riddle.answer }}</div>
            <!-- Riddle difficulty level -->
            <div style="float:left">
                <a href="{{url_for('main.level',riddle_id=riddle.id,direction='down')}}" class="level_down_up riddle_id" style="float:left">
                    <img src="/static/img/file-arrow-down-fill.svg" style="width:24px">
                </a>
                <div class="level" style="border:solid 1px;padding-left:10px; padding-right:10px;float:left">{{ riddle.level }}</div>
                <a href="{{url_for('main.level',riddle_id=riddle.id,direction='up')}}" class="level_down_up riddle_id">
                    <img src="/static/img/file-arrow-up-fill.svg" style="width:24px">
                </a>
            </div>
            <!-- ...............................-->
            <button class="btn btn-info btn-sm show_answer" >Afficher la réponse</button>
            <a href="update_riddle?riddle_id={{riddle.id}}" class="btn btn-primary btn-sm update_riddle riddle_id" title="Editer l'énigme">Modifier</a>
            <a href="delete_riddle?riddle_id={{riddle.id}}" class="btn btn-danger btn-sm delete_riddle riddle_id" title="Supprimer l'énigme">Supprimer</a>
            {% if current_user.admin %}
            <a href="#" data-toggle="tooltip" title="{{riddle.user}}" class="btn btn-dark btn-sm riddle_owner">{{riddle.user.username}}</a>
            {% endif %}


        <!-- Partie concernant les indices liés à l'énigme -->
        <!-- Balise destinée à indiquer à JQuery où insérer les clues -->

        <div class="clues">
            <div style="text-decoration:underline">Indices :</div>
            <div class="clue_list"></div>
        {% if riddle.clues|length > 0 %}
            <ul class="list-group">
                {% for clue in riddle.clues %}
                <div class="clueid" style="display:none">{{ clue.id }}</div>
                <li class="list-group-item">
                    {{ clue.clue }}
                    <a href="{{url_for('main.delete_clue',riddle_id=riddle.id,clue_id=clue.id)}}" class="btn btn-outline-danger btn-sm delete_clue riddle_id clue_id" style="float:right">Supprimer</a>
                    <a href="{{url_for('main.clue',riddle_id=riddle.id,clue_id=clue.id)}}" class="btn btn-outline-primary btn-sm riddle_id clue_id" style="float:right">Modifier</a>
                </li>
                {% endfor %}
            </ul>
        {% endif %}
            <a href="{{url_for('main.clue',riddle_id=riddle.id)}}" class="btn btn-outline-success btn-sm riddle_id" style="margin-top:10px">Ajouter un indice</a>
        </div>

    </div>
{% endfor %}

<!-- Zone test : pour affichage d'infos ! Effacer après tests -->
<div id="debug" style="border:2px solid red">Debug :<br/></div>
{% endblock %}

{% block footer %}
{{ macro.pagination_widget(pagination, 'main.list_riddle') }}

{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/list_riddle.js') }}"></script>
{% endblock %}

my_app/templates/main/main_clue.html
{{ form.csrf_token }}
{{ form.id() }}
{{ form.riddle_id() }}
<div class="form-group row" style="margin-bottom:10px">
    {{ form.riddle.label(class="col-sm-1 col-form-label") }}
    <div class="col-sm-8">
        {{ form.riddle(type="text",class="form-control") }}
    </div>
</div>
<div class="form-group row" style="margin-bottom:10px">
    {{ form.clue.label(class="col-sm-1 col-form-label") }}
    <div class="col-sm-8">
        {{ form.clue(type="text",class="form-control",placeholder="Encodez votre indice ici...") }}
    </div>
</div>

my_app/templates/main/update_clue.html
{% extends "main.html" %}
{% block body %}
<h1>Update clue :</h1>
<form method="POST" action="{{ url_for('main.save_clue') }}">
    {% include 'main/main_clue.html' %}
    {{ form.submit(class="btn btn-primary", value="Update") }}
</form>
{% endblock %}